Fix null pointer exception when gathering job parameters (JENKINS-63998)
jenkinsci/prometheus-plugin pull request #192
Opened 2020-12-07 06:26 UTC by motlib

Fixes https://issues.jenkins.io/browse/JENKINS-63998. This issue happens, because during gathering of the metrics a NullPointerException occurs when retreiving the job parameters. This exception is not handled, so the thread gathering the metrics is terminated without providing metrics.

Note: This is my first pull-request. If there are any formal issues with it, please tell me.

### Changes proposed

- Change the way the job parameter string is build, so that a job parameter with a "null" value does not cause a NullPointerException. This seems e.g. to happen for parameterized jobs with a SVN Tags parameter. 

### Checklist

- [ ] Includes tests covering the new functionality?
- [X] Ready for review
- [X] Follows CONTRIBUTING rules

### Notify

@markyjackson-taulia

2020-12-07 08:30 UTC, markyjackson-taulia requested changes
Is it possible to add a test?

2020-12-07 08:44 UTC, motlib commented
> Is it possible to add a test?

Hi Marky, I must say I have almost no experience with Java and Jenkins plugin development. I was glad to be able to build the plugin at all. I have no idea how to create tests yet.

2020-12-07 09:00 UTC, markyjackson-taulia commented
Okay, let me take a closer look at this tomorrow. I'm heading to sleep now (1 am for me)

2020-12-07 12:25 UTC, motlib commented
> Okay, let me take a closer look at this tomorrow. I'm heading to sleep now (1 am for me)

Let me know if I can support in any way. Getting a deeper understanding of plugin development will take some time for me. I will also check if one of my colleagues can perhaps help with this. But currently I cannot promise anything.

2020-12-07 13:57 UTC, markyjackson-taulia approved these changes

2020-12-07 13:57 UTC, merged

2021-02-15 13:23 UTC, EusebiusAditya commented
Are there any updates regarding this new release? @markyjackson-taulia